Tweet本文のフォント設定と背景色設定を使用する close #2
mikutter/message_detail_view pull request #3
Opened 2021-12-29 07:21 UTC by tsutsui

#2 の修正案です。
mikutter 本体側の core/mui/gtk_intelligent_textview.rb 側で
フォントと色の扱いを CSSで統一する仕組みが必要という気もしますが、
とりあえず雑対処で現状背景用で用意されている `style_provider` で
背景色とともにフォントの文字色も設定しています。

2021-12-31 10:55 UTC, toshia requested changes

2021-12-31 10:55 UTC, toshia commented on message_detail_view.rb
> +          background-color: rgb(#{bgcolor[0] / 256}, #{bgcolor[1] / 256}, #{bgcolor[2] / 256});
```suggestion
          color: #{css_rgb(fgcolor)};
          background-color: #{css_rgb(bgcolor)};
```

変換形式は同じなので、メソッドに切り出したほうが見やすそうです。
メソッドはこんな実装で。

```ruby
def css_rgb(uccolor)
  sprintf('#%02x%02x%02x', *uccolor.map { _1 >> 8 & 0xff })
end
```

irbにて確認
```
> css_rgb([0xffff, 0xcccc, 0x2323])
=> "#ffcc23"
```

UserConfigには、例えばRの強さに `0x80` を指定したい場合、8bit左シフトした結果とORを取って、 `0x8080` のようにして格納しているので、どちらか8bitを見ればOKです。

2022-01-02 18:41 UTC, tsutsui commented
とりあえず提案通りに直してみました。
動作も問題ないようです。

もともと `get_style_provider` の実装は mikutter 本体の gtk_postbox.rb
https://dev.mikutter.hachune.net/projects/mikutter/repository/main/revisions/99251b4bf774490e6843bcdc103f26178971e53b/entry/core/mui/gtk_postbox.rb#L383
からパクっているのですが、 従来 UserConfig設定 → GTK3用設定の変換のツールを gtk3.rb に用意すべきかもしれません。
まあ、変に公開で用意するとそれがまた互換性縛りになったりしそうですが。

2022-01-15 17:46 UTC, toshia approved these changes

2022-01-15 18:13 UTC, merged